# Generated by Django 4.1 on 2024-12-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_pv_post_uv'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_html',
            field=models.TextField(help_text='正文必须为Markdown格式', null=True, verbose_name='正文'),
        ),
    ]
