# Generated by Django 5.1.4 on 2025-01-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_content_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_html',
            field=models.TextField(editable=False, verbose_name='正文html代码'),
        ),
    ]
